<?php


namespace Test\WeChat\Providers;


use Illuminate\Support\Arr;
use Illuminate\Support\ServiceProvider;

class WeChatServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->mergeConfigFrom(__DIR__ . '/../Config/Config.php', 'data.wechat');
    }

    public function boot()
    {
        $this->loadMigrations();
        $this->loadWeChatConfig();
    }

    // 加载配置文件
    public function loadWeChatConfig()
    {
        // 根据默认连接的信息去database.php配置分属于goods组件的连接信息
        config(
            Arr::dot(
                config('database.connections.' . config('data.wechat.database.connection.type'), []),
                'database.connections.' . config('data.wechat.database.connection.name') . '.')
        );
        // 在把goods组件的单独信息 放到 database中的goods连接的信息
        config(
            Arr::dot(
                config('data.goods.database.' . config('data.goods.database.connection.name'), []),
                'database.connections.' . config('data.goods.database.connection.name') . '.')
        );
    }

    // 加载数据迁移
    public function loadMigrations()
    {
        if ($this->app->runningInConsole()) {
            parent::loadMigrationsFrom(__DIR__ . '/../Database/migrations'); // TODO: Change the autogenerated stub
        }
    }
}